[#noissue] Update validate commit workflow

diff --git a/.github/workflows/validate-commit.yml b/.github/workflows/validate-commit.yml
--- a/.github/workflows/validate-commit.yml
+++ b/.github/workflows/validate-commit.yml
@@ -12,10 +12,9 @@ jobs:
   validate-commit-messages:
     runs-on: ubuntu-22.04
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
       - name: Validate commit messages
+        env:
+          COMMIT: ${{ github.event.workflow_run.head_commit.message }}
         run: |
           # Define the regex for Conventional Commits
           commit_regex='^\[#(noissue|[0-9]+?)\].*'
@@ -25,14 +24,9 @@ jobs:
             [#1001] Refactor servermap
             [#noissue] Update README.md"
 
-          # Get the commit messages
-          commits=$(git log --format=%s origin/main..HEAD)
-
           # Validate each commit message
-          for commit in $commits; do
-            if ! echo "$commit" | grep -Eq "$commit_regex"; then
-              echo "$error_msg"
-              echo "Invalid commit message: $commit"
-              exit 1
-            fi
-          done
+          if ! echo "${COMMIT}" | grep -Eq "$commit_regex"; then
+            echo "$error_msg"
+            echo "Invalid commit message: $commit"
+            exit 1
+          fi
